In [14]:
%cd '/content/drive/MyDrive/Colab Notebooks/melody_generator_lstm/Data_pre_processing'

/content/drive/MyDrive/Colab Notebooks/melody_generator_lstm/Data_pre_processing


In [21]:
%run preprocess.ipynb

/content/drive/MyDrive/Colab Notebooks/melody_generator_lstm/Data_pre_processing
Loading songs...
Loaded 1700 songs.
Done
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]


In [22]:
import tensorflow as tf
import numpy as np
import os
import time
import tensorflow.keras as keras

In [23]:
OUTPUT_UNITS = 38
NUM_UNITS = [256]
LOSS = 'sparse_categorical_crossentropy'
LEARNING_RATE = 0.001
EPOCHS = 50
BATCH_SIZE = 64

In [24]:
def build_model(output_units, num_units, loss, learning_rate):
  # create the model architecture
  input = keras.layers.Input(shape=(None, output_units))
  x = keras.layers.LSTM(num_units[0])(input)
  x = keras.layers.Dropout(0.2)(x)

  output = keras.layers.Dense(output_units, activation='softmax')(x)

  model = keras.Model(input, output)
  #compile model
  model.compile(loss=loss, optimizer=keras.optimizers.Adam(learning_rate=learning_rate), metrics=['accuracy'])
  model.summary()
  return model

In [25]:
def train(output_units = OUTPUT_UNITS, num_units = NUM_UNITS, loss = LOSS, learning_rate = LEARNING_RATE):
  #generate the training sequences
  input, targets = generating_training_sequences(SEQUENCE_LENGTH)

  #define the model
  #build the network
  model = build_model(output_units, num_units, loss, learning_rate)

  #train model
  model.fit(inputs, targets, epochs = EPOCHS, batch_size=BATCH_SIZE)

  #save model
  model.save('model.h5')

In [26]:
train()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, None, 38)]        0         
                                                                 
 lstm_3 (LSTM)               (None, 256)               302080    
                                                                 
 dropout_3 (Dropout)         (None, 256)               0         
                                                                 
 dense_3 (Dense)             (None, 38)                9766      
                                                                 
Total params: 311846 (1.19 MB)
Trainable params: 311846 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/50
5659/5659 [==============================] - 41s 7ms/step - loss: 0.6864 - accuracy: 0.7894
Epoch 2/50
5659/5659 [==============================

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
